- hosts: all
  vars:
    KUBE_VERSION: "v1.30"
    FLANNEL_VERSION: ""
  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ hostname }}"

    - name: Apply k8s all config
      ansible.builtin.include_tasks: k8s/all.yml
