- name: K8S paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/apt/keyrings"
    - "/etc/containerd"

- name: K8S Update package cache
  ansible.builtin.package:
    update_cache: true

- name: K8S install prereqs
  apt:
    name: "{{ item }}"
  loop:
    - nfs-common
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - gnupg2
    - software-properties-common

- name: K8S load modules kernel
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: K8S modules for sysctl
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: K8S Disable Swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- ansible.builtin.include_tasks: containerd.yml

- name: K8S add keyring
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ KUBE_VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: K8S add gpg key
  apt_key:
    file: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: K8S add repository
  apt_repository:
    repo: "deb [arch=amd64] https://pkgs.k8s.io/core:/stable:/{{ KUBE_VERSION }}/deb/ /"

- name: K8S install cluster packages
  apt:
    name: "{{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: K8S fix version cluster packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: K8S enable kubelet
  ansible.builtin.systemd_service:
    enabled: true
    name: kubelet
