- name: ContainerD add gpg key docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ContainerD add repository docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: ContainerD install
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - cri-tools
    - containerd.io

- name: ContainerD generate default config
  command: mkdir -p /etc/containerd && containerd config default > /etc/containerd/config.toml

- name: ContainerD Config SystemdCgroup
  command: sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml

- name: ContainerdD restart and enable
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: containerd
